name: 02 - Workflow Events

on: 
    push: 
    pull_request: 
    schedule:
        - cron: '*/5 * * * *'   
    workflow_dispatch: # allows manual trigger from the GitHub UI

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
        - name: Show the trigger
          run: echo ${{ github.event_name }}